# Generated by Django 5.2.8 on 2025-12-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_moments_movie_alter_movie_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='genre_movie', to='movie_app.genre'),
        ),
    ]
